### ISSUE TITLE
dnssd-browse only browses once at start

### ISSUE THREAD

**Issue by 0xlee** [parasaurolophus/node-red-dnssd#1]
Hi,

thanks for building this useful tool for node-red.

I am missing one feature, browsing for a service regulary. For example, every 10 minutes, or at every input, which can be triggered.

The problem I am facing is, that my ipv6 addresses changes every 24 hour, and also all ip addresses in the thread network changes as well. Therefore, I have to browse again if the ip address changes, but there is no way of doing that.

What do you suggest? Do you have this use case in mind?

Best
Dongha

**Comment by parasaurolophus** [comment]
That is not a use case that I had in mind as my device IP addresses are fixed. But I've been thinking of adding the ability to trigger starting / restarting the browser as a way to recover from network errors, which I think might cover your requirement as well? Can't promise how soon I might get to it, but I'll keep your request in mind when I get back to this.

**Comment by parasaurolophus** [comment]
Added input message support to `dnssd-browser` node. Supports `start`, `stop` and `list` methods of `dnssd.Browser`. Browsers will no longer start automatically when flows start. Send `{"command":"start"}` in `msg.payload` to begin listening.

**Comment by 0xlee** [comment]
Thanks a lot!
I'll try it and give you a feedback.

**Comment by 0xlee** [comment]
I couldn't test it, because I don't find dnssd-browser on my node-red after updating package.
