### ISSUE TITLE
Crashes in 3.1

### ISSUE THREAD

**Issue by martenbiehl** [parasaurolophus/node-red-dnssd#2]
Hi,

I tried to use your package but it crashes with " [error] TypeError: sendEvent.destination.node.receive is not a function".

- I tested the example sketch and the error happens with advertisement and with browse.
- If I disable all inject nodes it works
- as soon as i send the start command as json, the crash happens and node-red fully exits

Any ideas where this could happen?

Best
Marten

**Comment by parasaurolophus** [comment]
To quote the age-old programmer's response to bug reports, "It works on my machine!" Can you send a small flow that demonstrates the issue?

**Comment by parasaurolophus** [comment]
p.s. I accidentally left out the updated examples flow in 3.1.0, which is why 3.1.1 popped up almost immediately. Are you encountering the same issue with the examples from 3.1.1?

**Comment by parasaurolophus** [comment]
Cannot reproduce. Please re-open with information on Node version, Node-RED version and steps to reproduce if it still occurs with version 3.1.3 or later.

**Comment by martenbiehl** [comment]
Hi @parasaurolophus,

sorry for the late response there was a weekend in between ;)

I was still running node-red 3.0.2, upgrading to 3.1 and node-red-dnssd to 3.1.3 fixed the error. Probably got caught in the middle of some changes.

Thanks for the great wrapper! Closed for good ;)

Best
Marten
